2018-04-12 18:41:58,454 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 2941275ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 18:49:28,532 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 410014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 19:16:54,650 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 665940ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 19:21:52,073 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 277399ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 21:22:29,508 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 7217418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 21:49:48,208 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 1618675ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 22:33:45,306 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 2617010ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-12 23:25:35,851 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 669759ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 01:17:03,008 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 4566799ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 03:01:25,389 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 6262369ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 04:49:21,465 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 6475804ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 06:37:28,544 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 6487069ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 08:25:37,972 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 6469387ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 09:54:29,195 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 5331157ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 09:56:40,720 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 111182ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

2018-04-13 11:16:07,703 ERROR 63113 nodejs.ClusterClientNoResponseError: client no response in 1386291ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 63113
hostname: whydeMacBook-Pro.local

